name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release
      run: v=$(gh release list |awk '{print $1}' |awk -F\. '{print $2}' |head -1); v=$(($v+1)); gh release create --draft --generate-notes v0.$v.0 gh-parallel
